### PR TITLE
Remove not found link to solid-tests

### PR DESCRIPTION
**Pull request by filhodanuvem**
I'm not sure if you guys need to open the repository solid-tests, I try to find it
with another name but I failed. If this is something which doesn't have a repository yet, this pull request
make sense.

### CODE REVIEW

**Comment by melvincarvalho** [comment]
@cloudson good catch!  Perhaps it got moved or archived.

@RubenVerborgh any idea what happened to this code?

**Comment by RubenVerborgh** [comment]
I've gone through the list of repositories that @justinwb and I checked, but solid-tests was not on them. So this repository did not exist as of August 2018.

**Comment by melvincarvalho** [comment]
@RubenVerborgh I think this was deleted in July

Do backups exist of the deleted repos?

**Comment by melvincarvalho** [comment]
> I've gone through the list of repositories that @justinwb and I checked, but solid-tests was not on them. So this repository did not exist as of August 2018.

Reopening this.  @RubenVerborgh please explain how it is possible that you deleted this repo (if you did) and that there was no back up.

How could this be possible?

We can not allow repositories to be deleted without backup.

The audit log contradicts your response.  I find this unprofessional, and I would recommend your access rights being audited.

**Comment by kjetilk** [comment]
We're going to restart this effort anyway. Please just let go.

**Pull request merged**
