### PR TITLE
Proposal: Solid ripples mechanism

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Proposed by @csarven and @rhiaro
Solid "ripples" is a pingback method for handling request notifications...

### CODE REVIEW

**Comment by melvincarvalho** [comment]
I dont mean to be a pain on this, but I just wanted to give a heads up on a possible naming clash in future.

There is a payments system for moving virtual currencies / points / credits between users in a decentralized way called "ripple"

https://en.wikipedia.org/wiki/Ripple_(payment_protocol)

This is one of the active inputs to some of the work going on in the payments group, and something that's been on my todo list for some time to implement in Solid (in the longer term).  Indeed the chair of the payments WG is an employee of Ripple inc., and we had two entries to the demo day written in nodejs from them.  With ripples (plural) being the name of their throttling currency.

If another name were selected e.g. like the original pingback, it may avoid future naming clashes.  Sorry to bring this up, I quite like the name otherwise. :)

**Comment by csarven** [comment]
@melvincarvalho Good feedback. I don't like the term 'ripples' myself.

**Comment by csarven** [comment]
I propose to close this PR (and not merge). I've created a proposal for "notifications": https://github.com/solid/solid/blob/notifications/proposals/notifications.md and that should supersede the ripples mechanism.

**Comment by melvincarvalho** [comment]
Sure, I didnt mean to hold up the merging.  Notifications.md looks interesting.  First impression, I like it!

**Comment by dmitrizagidulin** [comment]
Thanks Sarven! Closing this PR.

(Don't forget to actually create a PR with your `notifications` branch, when you're ready).

**Comment by csarven** [comment]
Thanks. Created https://github.com/solid/solid/pull/58

**Pull request closed without merging**
