### PR TITLE
Start list of contributors

### PR DESCRIPTION
**Pull request by RubenVerborgh**

### CODE REVIEW

**Review by rubensworks — APPROVED** [review]

**Comment by csarven** [comment]
Henry Story @bblfish https://bblfish.net/

**Review by csarven — APPROVED** [review]
Approving while acknowledging that the list is incomplete and in the process of getting updated.

**Comment by akuckartz** [comment]
How is "contributor" defined?

**Comment by RubenVerborgh** [comment]
I'm purposely trying to avoid a definition. If you feel you have contributed in any way (including, but not limited to, code, specs, issues, remarks, suggestions, chats, support, UI, UX, managing…) and want to be listed, please let me now or add yourself.

**Review by justinwb — APPROVED** [review]
Language on how people can get added if they feel they're being left out looks sufficient - which is important. Looks good!

**Review by kidehen — APPROVED** [review]

**Review by megoth — APPROVED** [review]

**Comment by dan-f** [comment]
Thanks for picking this up, @RubenVerborgh!

All the names I could think of are on the list, though I'm sure there are others out there.

**Review by dan-f — APPROVED** [review]

**Review by dmitrizagidulin — APPROVED** [review]
👍

**Comment by RubenVerborgh** [comment]
Thanks all, given that I haven't heard of any blockers, I will go ahead and merge. Please suggest more people for inclusion into this list through new PRs.

**Comment by slorber** [comment]
Hi,

Just wanted to mention https://github.com/all-contributors/all-contributors

**Pull request merged**
