### PR TITLE
Quick update to remove outdated information

### PR DESCRIPTION
**Pull request by RubenVerborgh**

### CODE REVIEW

**Comment by TallTed** [comment]
I suggest an associated issue be created, to make it easier to look back at what was removed, and to make it more likely that appropriate info be added sooner than later.  That issue should not be closed until the new info has indeed been added.

**Comment by RubenVerborgh** [comment]
Check! Done in https://github.com/solid/solid/issues/280

**Review by kay-kim — APPROVED** [review]
lgtm -- I'm not usually on these solid repos (just the the solidproject one), but the removal of obsolete content seems good to me.

**Comment by jeff-zucker** [comment]
LGTM - fewer places to keep updated.

**Pull request merged**
